### ISSUE TITLE
Index out of range after failing to fetch

### ISSUE THREAD

**Issue by Ullaakut** [Ullaakut/astronomer#40]
```
Beginning fetching process for repository icecrime/poule
Pre-fetching all stargazers...ok
  > All 216 stargazers will be scanned
This repository appears to have a low amount of stargazers. Trust calculations might not be accurate.
Fetching contributions for 216 users up to year 2013
 [=>------------------------------------------------------------] ETA: 6h13m23s Elapsed: 9m34s Progress: 3 %
Failed to fetch user contributions from GitHub API too many times.
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/ullaakut/astronomer/pkg/gql.FetchContributions(0xc00021bf30, 0xc000176300, 0xa, 0x10, 0x7dd, 0x0, 0x100, 0x14fc936, 0x32, 0xc0001bfbb8)
	/Users/ullaakut/Work/go/src/github.com/ullaakut/astronomer/pkg/gql/fetch.go:315 +0x1992
main.detectFakeStars(0xc00021bf30, 0x14e7be3, 0x7)
	/Users/ullaakut/Work/go/src/github.com/ullaakut/astronomer/main.go:106 +0x3f8
main.main()
	/Users/ullaakut/Work/go/src/github.com/ullaakut/astronomer/main.go:80 +0x4b9
```

**Comment by Ullaakut** [comment]
Fixed in #41
